version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"  # Using 8081 to avoid conflict with Airflow
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8080
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    user: root

volumes:
  jenkins-data: