version: '3.8'
services:
  prefect-server:
    image: prefecthq/prefect:2.14-python3.11
    ports:
      - "4200:4200"
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
    command: prefect server start --host 0.0.0.0
    volumes:
      - prefect-data:/root/.prefect
      - ./flows:/opt/prefect/flows
    restart: unless-stopped

  prefect-worker:
    image: prefecthq/prefect:2.14-python3.11
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    command: prefect worker start --pool default-agent-pool
    volumes:
      - ./flows:/opt/prefect/flows
    depends_on:
      - prefect-server
    restart: unless-stopped

volumes:
  prefect-data: