apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: flask-react-app
  labels:
    app: flask-backend
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
        component: backend
    spec:
      containers:
      - name: flask-backend
        image: localhost:5000/flask-react-backend:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: FLASK_ENV
          value: "production"
        - name: DATABASE_URL
          value: "sqlite:///app.db"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: jwt-secret
        - name: CORS_ORIGINS
          value: "http://localhost:3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: app-data
          mountPath: /app/instance
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: flask-backend-pvc
      restartPolicy: Always
      securityContext:
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
  namespace: flask-react-app
  labels:
    app: flask-backend
spec:
  selector:
    app: flask-backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-backend-pvc
  namespace: flask-react-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
  namespace: flask-react-app
type: Opaque
data:
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24=  # base64 encoded